site_name: plottools

site_url: https://bendalab.github.io/plottools/

repo_url: https://github.com/bendalab/plottools/

edit_uri: ""

site_author: Benda-Lab

theme: readthedocs

markdown_extensions:
    - markdown_include.include
    
nav:
    - Home: 'index.md'
    - 'Tutorial':
        - 'Getting started with matplotlib': 'starter.md'
        - 'Plotting guidelines': 'guide.md'
        - 'Coding a figure': 'code.md'
        - 'How to structure your code': 'structure.md'
    - 'User Guide':
        - 'Colors': 'colors.md'
        - 'Figure': 'figure.md'
        - 'Subplots': 'subplots.md'
        - 'Spines': 'spines.md'
        - 'Ticks': 'ticks.md'
        - 'Insets': 'insets.md'
        - 'Scalebars': 'scalebars.md'
    - API reference: 'api/index.html'
