dist: xenial

language: python

matrix:
    include:
        - python: "3.6"
          os: linux

before_install:
  - pip install -U pip

install:
#  - pip install numpy
#  - pip install nose nose-cov
#  - pip install codecov
  - pip install -r requirements.txt
  - pip install pdoc3
  - pip install markdown-include
  - pip install mkdocs

script:
#  - nosetests -vv --with-coverage --cover-package=plottools
  - ./build-docs.sh

#after_success:
#  - codecov

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
  on:
      branch: master
